### ISSUE TITLE
Question I Suppose

### ISSUE THREAD

**Issue by Mattabase** [CerulanLumina/HealthHungerTweaks#24]
Hey, So dig the changes to the new update I do have question, what are the odds the other tiers of health kits could come back? I use this in a modpack with no natural regen, but because the recipe for health kits a much more expensive and only have once choice healing has become exponentially harder. Iron is really scarce in the the pack so having kits made from sticks and plant matter was really important.

**Comment by LuminaSapphira** [comment]
I get where you're coming from. I'll consider re-adding the direct health kits, though there will likely be only two (a basic and an advanced one). Additionally, your comment about the health regen being disabled reminded me of an edge case where the regen is disabled, then its possible the kit wouldn't even work in the first place, because it uses the same regen values as the auto-regeneration. 

Good thing this is only a beta!

I'll close this issue, but keep a lookout for related issues pertaining to what I wrote about.

**Comment by Mattabase** [comment]
Thank you very much for the response. =)
