### ISSUE TITLE
Support for ToughAsNails (1.12)

### ISSUE THREAD

**Issue by ghost** [CerulanLumina/HealthHungerTweaks#9]
we really need it, TAN mod completely handles the health regen. system. so HHT doesn't work in actually :( please do support/fix for it. thanks

**Comment by LuminaSapphira** [comment]
Can you tell what exactly I need to support? The default configurations for both mods seem to work fine. https://streamable.com/gdfdd

**Comment by ghost** [comment]
there are 2 problems:
1- if thirst level isn't full, health doesn't regenerates.
2- if TAN installed, health regen system (as config says) doesn't work. for example:
i did I:delayUntilStart=40 and I:delayBetweenTicks=40
but it regenerates much slower (just like vanilla)

**Comment by ghost** [comment]
at least you can add a config like "MinimumThirst" (as a TAN support). it would be awesome and also a solution for this issue.

**Comment by LuminaSapphira** [comment]
What version of TAN are you using? I still can't reproduce (still regenerating at 1 drop).

Also those config options will make regeneration only be a half heart every 2 seconds, rather than the default half heart every 1/2 second. The default is 200 until start and 10 between regen ticks.

I can look into adding a minimum thirst option for integration however.

A video with the config options you specify: https://streamable.com/d9x9a

**Comment by ghost** [comment]
minimum thirst option would be awesome. using ToughAsNails-1.12-3.0.0.62-universal and latest your mod

**Comment by LuminaSapphira** [comment]
Alright no guarantees about it, depends on the accessibility of the API, will be out next update if I can, but are you still experiencing the other issues? If so could you give me a complete list of mods used and potentially their configurations?

**Comment by ghost** [comment]
ah yes of course, here it is:
https://github.com/kenijey/Ezteria

**Comment by LuminaSapphira** [comment]
ToughExpansion is causing the issue. It's also non-configurable as to the required thirst (though you _can_ turn it off). I should be able to implement minimum thirst in my mod, but if you're using ToughExpansion you would have to disable its minimum thirst checking as they would be mutually exclusive.

**Comment by LuminaSapphira** [comment]
Pushed an update (2.1.0-alpha1) that has experimental TAN thirst integration.

**Comment by ghost** [comment]
oh... it's really interesting. thank you.

**Comment by ghost** [comment]
hey ah, it doesn't work again :/ you can see my modpack github page. hope commits help you :(

**Comment by ghost** [comment]
and ah let me tell what problem i experienced exactly, i had full hunger and %80 thirst and my health wasn't regenerating. (stayed on 2/10 hearts)

**Comment by LuminaSapphira** [comment]
It doesn't look like you've disabled ToughExpansion's thirst checking in its config. Unfortunately due to the way Forge events work, my mod's thirst checking won't be able to work alongside ToughExpansion's. You will have to disable ToughExpansion's minimum thirst checking. (Which isn't a problem, as my mod will do the same thing, but offer more granular control over the required level.)
